# Use root/example as user/password credentials
version: '3.7'
services:
  main_db:
    image: mongo:5.0.9
    container_name: main_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - main_db:/data/db

volumes:
  main_db:
